# This is a basic workflow to help you get started with Actions

name: Build TF Lite for windows

# Controls when the workflow will run

on:

  workflow_call:
    inputs:
      TF_VERSION:
        type: string
        required: true
      BUILD_OPTIONS:
        type: string
        required: false

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      TF_VERSION:
        description: 'Enter the tensorflow branch name on which the TF Lite binaries should be built.'
        required: true
        default: "v2.17.0"
      BUILD_OPTIONS:
        description: 'Enter the build options with which TF Lite binaries should be built.'
        required: false
        default: "-DTFLITE_ENABLE_XNNPACK=ON -DTFLITE_ENABLE_GPU=ON"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Get TensorFlow
      uses: actions/checkout@v4
      with:
        repository: tensorflow/tensorflow
        path: tensorflow_src
        ref: ${{ github.event.inputs.TF_VERSION }}

    - name: Get patches
      uses: actions/checkout@v4
      if: ${{ hashFiles(patches/${{ github.event.inputs.TF_VERSION }}.patch) != '' }}
      ref: ${{ github.ref }}
      path: tflite-binaries

    - name: Patch TF Lite
      if: ${{ hashFiles(patches/${{ github.event.inputs.TF_VERSION }}.patch) != '' }}
      run: |
        cd tensorflow_src
        PATCH_PATH=../tflite-binaries/patches/${{ github.event.inputs.TF_VERSION }}.patch
        [ -f ${PATCH_PATH} ] && git apply ${PATCH_PATH}

    - name: Build TF Lite
      run: |
        mkdir tflite_build
        cd tflite_build
        cmake ../tensorflow_src/tensorflow/lite/c ${{ github.event.inputs.BUILD_OPTIONS }}
        cmake --build . -j --config Release
        
    - name: output CWD
      run: ls tflite_build/
          
    - name: Upload TF Lite build 
      uses: actions/upload-artifact@v4
      with:
        name: tensorflowlite_c-win.dll
        path: tflite_build/Release/tensorflowlite_c.dll
